### PR TITLE
linting Dockerfile

### PR DESCRIPTION
**Pull request by PatMyron**
https://github.com/hadolint/hadolint/wiki/DL3017
https://github.com/hadolint/hadolint/wiki/DL3019

---

Awesome idea, btw!

### CODE REVIEW

**Comment by ScottBrenner** [comment]
Nice, wonder why the checks didn't trigger .. https://github.com/ScottBrenner/cfn-lint-action/pull/2/checks

Thanks! Going to merge regardless 👍

**Comment by PatMyron** [comment]
Think that Github workflow is currently configured to only run after pushes:

```hcl
  on = "push"
```

https://github.com/ScottBrenner/cfn-lint-action/blame/fec199a07efa0f35dba0918ab9cc828490fbcdf8/.github/main.workflow#L2

**Comment by ScottBrenner** [comment]
Right, [the `push` event is triggered a push to a repository branch](https://developer.github.com/v3/activity/events/types/#pushevent). My commit on the previous pull request triggered checks https://github.com/ScottBrenner/cfn-lint-action/pull/1

**Comment by PatMyron** [comment]
Wondering if it's because my pull request was from another repository. `pull_request` is another event option though

**Comment by ScottBrenner** [comment]
Interesting, you had forked this repository right? [The checks should've run on your fork, in that case](https://github.community/t5/GitHub-API-Development-and/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/m-p/15746/highlight/true#M415). More details [here](https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#pull-request-events-for-forked-repositories), good to know!

**Pull request merged**
