### PR TITLE
Use Action from GitHub Marketplace

### PR DESCRIPTION
**Pull request by ScottBrenner**
Use latest version of Action from GitHub Marketplace, don't push to Docker Hub.

### CODE REVIEW

**Comment by softprops** [comment]
Won't this mean users will have to rebuild the docker image on every workflow run?

The benefit of having a prebuilt image was amortizing that time.

**Comment by ScottBrenner** [comment]
> Won't this mean users will have to rebuild the docker image on every workflow run?

Yes, that's correct. Hardly takes a minute in my testing and ensures that people always use the most recent version, as I inconsistently build/tag/push Docker images as releases.

That said, certainly open to revisiting this using [GitHub's new Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

**Comment by softprops** [comment]
I believe that was the first try. Things may have changed but the issue discovered from the previous attempt was that it wasn't supported as a host for public images

https://github.com/ScottBrenner/cfn-lint-action/issues/10

**Comment by ScottBrenner** [comment]
Ah right, will re-look it again.

**Pull request merged**
